apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*

build:
  # by default, when skaffold rebuilds an image, it'll try to push to docker so this setting disables that
  local:
    push: false
  # this is saying there is some pod running code from our client dir and if there is a change in the client dir, then skaffold will try to take those changes and apply them to our pod
  artifacts:
    - image: jpwaves/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        # this will take the change in a specific file and throw it into the pod
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: jpwaves/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        # this will take the change in a specific file and throw it into the pod
        manual:
          - src: '*.js'
            dest: .
    - image: jpwaves/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        # this will take the change in a specific file and throw it into the pod
        manual:
          - src: '*.js'
            dest: .
    - image: jpwaves/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        # this will take the change in a specific file and throw it into the pod
        manual:
          - src: '*.js'
            dest: .
    - image: jpwaves/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        # this will take the change in a specific file and throw it into the pod
        manual:
          - src: '*.js'
            dest: .
    - image: jpwaves/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        # this will take the change in a specific file and throw it into the pod
        manual:
          - src: '*.js'
            dest: .